version: '3.8'
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '9090:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
